### ISSUE TITLE
Não considerando quebra de linhas do atributo @obs

### ISSUE THREAD

**Issue by AlencarGabriel** [robsonrosilva/protheusDoc#1]
Identificado que na área de "outras informações", o atributo `@obs` não está retornando o texto completo quando há quebra de linhas.

Exemplo:

![OBS](https://user-images.githubusercontent.com/10109480/82211796-ccdb1a80-98e7-11ea-9d69-13f9a705458d.png)
![OBS2](https://user-images.githubusercontent.com/10109480/82211794-cc428400-98e7-11ea-801f-3f5f66a0c2d7.png)

**Comment by robsonrosilva** [comment]
Problema corrigido na versão 1.1.1.

**Comment by AlencarGabriel** [comment]
![Anotação 2020-05-28 083935](https://user-images.githubusercontent.com/10109480/83137029-ce15ff80-a0be-11ea-9997-1e57b71173b8.png)

Funcionou certinho. Já lanço a melhoria na extensão.
