### ISSUE TITLE
Parte do texto nas descrições não é documentado

### ISSUE THREAD

**Issue by AlencarGabriel** [robsonrosilva/protheusDoc#2]
Detalhamento do problema está reportado na issue: https://github.com/AlencarGabriel/ProtheusDoc-VsCode/issues/35#issue-658447201

**Comment by robsonrosilva** [comment]
@AlencarGabriel  favor teste a versão 1.1.2 consegui reproduzir e corrigir a forma de tratar essas tags.

**Comment by AlencarGabriel** [comment]
Obrigado pela rápida intervenção no problema @robsonrosilva , vou atualizar aqui e validar. Te posiciono.

**Comment by AlencarGabriel** [comment]
Teste realizado, e problema resolvido na v1.1.2:

![image](https://user-images.githubusercontent.com/10109480/87813315-07a1f600-c838-11ea-9e93-c7dc6d65ecee.png)
