### ISSUE TITLE
Parâmetro Opcional no ProtheusDoc

### ISSUE THREAD

**Issue by AlencarGabriel** [robsonrosilva/protheusDoc#4]
Criar tratamento na documentação HTML para considerar parâmetros opcionais.

Solicitação feita na seguinte issue: AlencarGabriel/ProtheusDoc-VsCode#50

**Comment by AlencarGabriel** [comment]
Resultado da implementação:

![image](https://user-images.githubusercontent.com/10109480/111354645-4b6a2b00-8665-11eb-9538-3cf914420674.png)

**Comment by AlencarGabriel** [comment]
@robsonrosilva ,

poderia subir uma nova versão no npm com essa modificação?

**Comment by robsonrosilva** [comment]
Versão publicada.

**Comment by AlencarGabriel** [comment]
Obrigado meu caro!
