### ISSUE TITLE
Adaptação da Tag @see com Múltiplos

### ISSUE THREAD

**Issue by AlencarGabriel** [robsonrosilva/protheusDoc#5]
Considerar as múltiplas tags `@see` de uma documentação ProtheusDoc nos HTML.

Solicitação feita na issue: AlencarGabriel/ProtheusDoc-VsCode#61

**Comment by robsonrosilva** [comment]
@AlencarGabriel vou colocar esses itens que podem ser múltiplos como array, assim todos vão ser listados.
